[options]
girs_dir = "../gir-files"
library = "Granite"
version = "1.0"
min_cfg_version = "5.5"
target_path = "."
work_mode = "normal"
deprecate_by_min_version = true

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
    "Gee",
    "Gdk",
    "GdkPixbuf",
    "Gtk",
    "Pango",
    "Cairo",
]

generate = [
    "Granite.Application",
]

manual = [
    "Granite.HeaderLabel",
    "Granite.WidgetsWelcome",
]
