// This file was generated by gir (https://github.com/gtk-rs/gir @ 00040a2)
// from gir-files (https://github.com/gtk-rs/gir-files @ 34af997)
// DO NOT EDIT

mod application;
pub use self::application::{Application, NONE_APPLICATION};
pub use self::application::ApplicationExt;

#[doc(hidden)]
pub mod traits {
    pub use super::ApplicationExt;
}
