// This file was generated by gir (https://github.com/gtk-rs/gir @ 00040a2)
// from gir-files (https://github.com/gtk-rs/gir-files @ 7c3d3f5+)
// DO NOT EDIT

mod application;
pub use self::application::{Application, NONE_APPLICATION};
pub use self::application::ApplicationExt;

mod widgets_welcome;
pub use self::widgets_welcome::{WidgetsWelcome, NONE_WIDGETS_WELCOME};
pub use self::widgets_welcome::WidgetsWelcomeExt;

#[doc(hidden)]
pub mod traits {
    pub use super::ApplicationExt;
    pub use super::WidgetsWelcomeExt;
}
